package com.walletconnect.android.common.di

enum class AndroidCommonDITags {
    MOSHI, INTERCEPTOR, OK_HTTP, RELAY_SERVICE, SCARLET, MSG_ADAPTER, CONNECTION_CONTROLLER, LIFECYCLE, LOGGER, CONNECTIVITY_STATE
}