name: 'Setup Required files'
description: 'Setup required files for building samples'

inputs:
  GOOGLE_SERVICES_JSON:
    description: 'Google Services Json file'
    required: true
  FIREBASE_SERVICE_CREDENTIALS:
    description: 'Firebase Service Credentials file'
    required: true
  SECRETS_PROPERTIES:
    description: 'Secrets properties file'
    required: true
  ENCODED_STRING_DEBUG:
    description: 'Encoded string for debug keystore'
    required: true
  SIGNING_KEY_STORE_PATH_DEBUG:
    description: 'Path to store debug keystore'
    required: true
  ENCODED_STRING_INTERNAL:
    description: 'Encoded string for internal keystore'
    required: true
  SIGNING_KEY_STORE_PATH_INTERNAL:
    description: 'Path to store internal keystore'
    required: true
  ENCODED_STRING_UPLOAD:
    description: 'Encoded string for upload keystore'
    required: true
  SIGNING_KEY_STORE_PATH_UPLOAD:
    description: 'Path to store upload keystore'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        architecture: x86_64
        cache: 'gradle'

    - name: Accept Android Licenses
      uses: SimonMarquis/android-accept-licenses@v1

    - name: Create Google Services Json File - Wallet
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > ./sample/wallet/google-services.json

    - name: Create Google Services Json File - Dapp
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > ./sample/dapp/google-services.json

    - name: Create Google Services Json File - Modal
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > ./sample/modal/google-services.json

    - name: Create Firebase Service Credentials file
      shell: bash
      env:
        FIREBASE_SERVICE_CREDENTIALS: ${{ inputs.FIREBASE_SERVICE_CREDENTIALS }}
      run: echo $FIREBASE_SERVICE_CREDENTIALS | base64 --decode > credentials.json

    - name: Fetch Properties File
      shell: bash
      env:
        SECRETS_PROPERTIES: ${{ inputs.SECRETS_PROPERTIES }}
      run: echo $SECRETS_PROPERTIES | base64 --decode > secrets.properties

    - name: Decode Debug Keystore
      shell: bash
      env:
        ENCODED_STRING_DEBUG: ${{ inputs.ENCODED_STRING_DEBUG }}
        SIGNING_KEY_STORE_PATH_DEBUG: ${{ inputs.SIGNING_KEY_STORE_PATH_DEBUG }}
      run: |
        echo $ENCODED_STRING_DEBUG | base64 --decode > $SIGNING_KEY_STORE_PATH_DEBUG

    - name: Decode Internal Keystore
      shell: bash
      env:
        ENCODED_STRING_INTERNAL: ${{ inputs.ENCODED_STRING_INTERNAL }}
        SIGNING_KEY_STORE_PATH_INTERNAL: ${{ inputs.SIGNING_KEY_STORE_PATH_INTERNAL }}
      run: |
        echo $ENCODED_STRING_INTERNAL | base64 --decode > $SIGNING_KEY_STORE_PATH_INTERNAL

    - name: Decode Upload Keystore
      shell: bash
      env:
        ENCODED_STRING_UPLOAD: ${{ inputs.ENCODED_STRING_UPLOAD }}
        SIGNING_KEY_STORE_PATH_UPLOAD: ${{ inputs.SIGNING_KEY_STORE_PATH_UPLOAD }}
      run: |
        echo $ENCODED_STRING_UPLOAD | base64 --decode > $SIGNING_KEY_STORE_PATH_UPLOAD