package com.walletconnect.android.impl.di

enum class AndroidCoreDITags {
    SERIALIZER_SET,
    DESERIALIZER_MAP,
    ANDROID_CORE_DATABASE_DRIVER,
    ANDROID_CORE_DATABASE,
    COLUMN_ADAPTER_LIST,
    COLUMN_ADAPTER_APPMETADATATYPE
}