package com.walletconnect.android.impl.di

enum class AndroidCoreDITags {
    DB_ALIAS,
    DB_KEY_STORAGE,
    DB_SECRET_KEY,
    DB_PASSPHRASE,
    ANDROID_CORE_DATABASE,
    ANDROID_CORE_DATABASE_DRIVER,
    COLUMN_ADAPTER_LIST,
    COLUMN_ADAPTER_APPMETADATATYPE
}