-keep class com.walletconnect.web3.wallet.client.Wallet$Model$Cacao$Signature { *; }
-keep class com.walletconnect.web3.wallet.client.Wallet$Model$Cacao { *; }
-keep class com.walletconnect.web3.wallet.client.Wallet$Model { *; }
-keep class com.walletconnect.web3.wallet.client.Wallet { *; }