package com.walletconnect.android.di

enum class AndroidCoreDITags {
    ANDROID_CORE_DATABASE_DRIVER,
    ANDROID_CORE_DATABASE,
    COLUMN_ADAPTER_LIST,
    COLUMN_ADAPTER_APPMETADATATYPE,
    COLUMN_ADAPTER_MAP,
    COLUMN_ADAPTER_VALIDATION
}