package com.walletconnect.android.api

enum class AndroidApiDITags {
    MOSHI, INTERCEPTOR, OK_HTTP, RELAY_SERVICE, SCARLET, MSG_ADAPTER, CONNECTION_CONTROLLER, LIFECYCLE, LOGGER, CONNECTIVITY_STATE
}